### ISSUE TITLE
broken link in several readmes

### ISSUE THREAD

**Issue by AaronKutch** [udoprog/musli#14]
In https://crates.io/crates/musli-storage under the "Configuring" section, the "Encoding" link is broken, this is also the case for some other readmes. Also, at the workspace level Cargo.toml I would recommend adding `resolver = "2"` under the `[workspace]` section.

**Comment by AaronKutch** [comment]
musli-value should have "alloc" in its default features (and add `default-features = false` as necessary elsewhere), because otherwise all the `Value` variants are not showing up in docs.rs

**Comment by udoprog** [comment]
Thanks!

**Comment by AaronKutch** [comment]
I don't see a non-alloc integration test, in my experience it is pretty easy to accidentally introduce an allocation dependency, I use https://github.com/AaronKutch/awint/tree/main/no_alloc_test to verify that no_alloc targets compile correctly

**Comment by AaronKutch** [comment]
Additionally, since this is a crate that is involving bit packing and simd and stuff, I would highly recommend additionally running the test suite on a 32 and 64 bit big endian system (e.x. I do this [here](https://github.com/AaronKutch/awint/blob/71b35e8f034126d416d435fd718a2a6b95e94c4a/.github/workflows/ci.yml#L129)). These are just nitpicks, I have to say that the overall design and existing testing looks almost flawless.

**Comment by AaronKutch** [comment]
When I open up documentation locally and online I get a lot of "Query parser error: "Unexpected ."." errors when trying to follow links, they all take the form `[StructOrTrait]: https://link`. A lot of the specifiers aren't needed, `cargo-doc` will take care of generating the urls for you. For example, in the `//!` comments of `musli_common` you should be able to remove the `[Reader]: ....` and `[Writer]: ...` lines at the bottom, and edit the uses of `[Reader]` to be things like `[reader::Reader]` or `[Reader](reader::Reader)`

**Comment by AaronKutch** [comment]
Many more links can be replaced by `[crate_name::...]` if `crate_name` is in the dependency tree, this would mean that if I am searching documentation offline, it will not regularly boot me to online, and will be more maintainable.

**Comment by AaronKutch** [comment]
Just to make sure, the `UsizeEncoding` in `Encoding` only applies to collection lengths? `Encoding` should probably have more description in its docs. I would recommend making 64 bits be the default for fixed settings, especially if it could be applied to things intended for storage.

**Comment by AaronKutch** [comment]
I notice that in the implementation of `Encode` for `Result`, it uses `0usize` and `1usize` for the `first: F` argument, does this eventually result in optimal encoding down the line? Enum tagging is the only suspicious thing I'm seeing, could musli handle niche optimizations?

**Comment by AaronKutch** [comment]
The docs say `MAX_INLINE_LEN` is 62, but the source code says 30. The docs need to describe what pack size is and what units it is in.

**Comment by udoprog** [comment]
Let's see...

* Adding a no-std/no-alloc test is a good idea.
* The amount of bit fiddling is minimal, but I'll accept integration tests if they can run through github actions (qemu should work?).
* Documentation links in the toplevel comments have to be http:// links, since they're used to generate the README. If the readme tool I'm using could resolve Rust types and translate them to docs.rs links automatically that would be great though. For now this is the best compromise.
* Various documentation errors. They are bound to happen :). If you can, please fix them!
* More documentation is always nice. Elaborating on the Encoding interfaces is kinda important though, so I agree it should be elaborated.

If you want to make sure things get fixed it would be helpful to open specific issues for them. For now I'll be adopting some of these things on my personal backlog. But I have a lot of things to do right now. So we'll see!

Thank you!

**Comment by AaronKutch** [comment]
Oh and regarding the two tests I proposed, they don't need to be configured to run for every PR, just for every tag before release, since they can take a lot of Actions minutes to complete
