### ISSUE TITLE
Document no_std, no_alloc capabilities.

### ISSUE THREAD

**Issue by t-moe** [udoprog/musli#68]
It would be nice if the readme or the doc would make it clear which crates/formats are well suited for no_std or even no_alloc environments. I see that you support no_std in general, but it is not clear to me which formats can be used by using static allocations only (no_alloc , no global allocator). 

Thank you.

**Comment by udoprog** [comment]
Right!

All of them should be able to, [an example is provided for musli-json](https://github.com/udoprog/musli/blob/main/crates/no-std-examples/examples/no-std-json.rs), but the same pattern should be usable across all formats that provide `encode_with` and `from_slice_with`.
* musli-storage [`encode_with`](https://docs.rs/musli-storage/latest/musli_storage/encoding/struct.Encoding.html#method.encode_with) / [`from_slice_with`](https://docs.rs/musli-storage/latest/musli_storage/encoding/struct.Encoding.html#method.from_slice_with).
* musli-wire [`encode_with`](https://docs.rs/musli-wire/latest/musli_wire/encoding/struct.Encoding.html#method.encode_with) / [`from_slice_with`](https://docs.rs/musli-wire/latest/musli_wire/encoding/struct.Encoding.html#method.from_slice_with).

I did just note that such methods are not made available for `musli-descriptive`, but that is just an oversight. They are fairly straight forward to add ([missing this macro call](https://docs.rs/musli-storage/latest/src/musli_storage/encoding.rs.html#245)).

If you'd want to, feel free to extend the README with the above information and add the missing impls for `musli-descriptive`. Otherwise I'll eventually get to it :)
